# Generated by Django 4.0.4 on 2022-05-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0004_customer_address_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
